version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: exoplanet-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - proxy-network
    restart: always

  frontend:
    build:
      context: ./exoplanets
    container_name: exoplanet-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - proxy-network


networks:
  proxy-network:
    external:
      name: proxy_proxy-network  # Replace with the actual name from 'docker network ls'
