version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: exoplanet-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - proxy-network
    restart: always

  frontend:
    build:
      context: ./exoplanets
    container_name: exoplanet-frontend
    depends_on:
      - backend
    restart: always
    environment:
      - VIRTUAL_HOST=212.67.9.175
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
