version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: exoplanet-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - proxy-network
    restart: always

  frontend:
    build:
      context: ./exoplanets
    container_name: exoplanet-frontend
    depends_on:
      - backend
    restart: always
    environment:
      - VIRTUAL_HOST=212.67.9.175
      - VIRTUAL_PORT=80
    networks:
      - proxy-network
    # ⛔ ports тут НЕ НУЖЕН, иначе конфликт с nginx-proxy
    # ⛔ letsencrypt тоже не нужен, так как нет домена

networks:
  proxy-network:
    external: true

